var isoCountries = {
	'Argentina': 'AR',
	'Australia': 'AU',
	'Austria': 'AT',
	'Belgium': 'BE',
	'Brazil': 'BR',
	'Bulgaria': 'BG',
	'Canada': 'CA',
	'China': 'CN',
	'Colombia': 'CO',
	'Cuba': 'CU',
	'Czech Republic': 'CZ',
	'Egypt': 'EG',
	'France': 'FR',
	'Germany': 'DE',
	'Greece': 'GR',
	'Hong Kong': 'HK',
	'Hungary': 'HU',
	'India': 'IN',
	'Indonesia': 'ID',
	'Ireland': 'IE',
	'Israel': 'IL',
	'Italy': 'IT',
	'Japan': 'JP',
	'Korea': 'KR',
	'Latvia': 'LV',
	'Lithuania': 'LT',
	'Malaysia': 'MY',
	'Mexico': 'MX',
	'Morocco': 'MA',
	'Netherlands': 'NL',
	'New Zealand': 'NZ',
	'Nigeria': 'NG',
	'Norway': 'NO',
	'Philippines': 'PH',
	'Poland': 'PL',
	'Portugal': 'PT',
	'Romania': 'RO',
	'Russian Federation': 'RU',
	'Saudi Arabia': 'SA',
	'Serbia': 'RS',
	'Singapore': 'SG',
	'Slovakia': 'SK',
	'Slovenia': 'SI',
	'South Africa': 'ZA',
	'Sweden': 'SE',
	'Switzerland': 'CH',
	'Taiwan': 'TW',
	'Thailand': 'TH',
	'Turkey': 'TR',
	'Ukraine': 'UA',
	'United Arab Emirates': 'AE',
	'United Kingdom': 'GB',
	'England': 'GB',
	'United States': 'US',
	'Venezuela': 'VE',
	// /\ Supported Countries
	// \/ Unsupported countries
	//'Afghanistan': 'AF',
	//'Aland Islands': 'AX',
	//'Albania': 'AL',
	//'Algeria': 'DZ',
	//'American Samoa': 'AS',
	//'Andorra': 'AD',
	//'Angola': 'AO',
	//'Anguilla': 'AI',
	//'Antarctica': 'AQ',
	//'Antigua And Barbuda': 'AG',
	//'Armenia': 'AM',
	//'Aruba': 'AW',
	//'Armenia': 'AM',
	//'Aruba': 'AW',
	//'Azerbaijan': 'AZ',
	//'Bahamas': 'BS',
	//'Bahrain': 'BH',
	//'Bangladesh': 'BD',
	//'Barbados': 'BB',
	//'Belarus': 'BY',
	//'Belize': 'BZ',
	//'Benin': 'BJ',
	//'Bermuda': 'BM',
	//'Bhutan': 'BT',
	//'Bolivia': 'BO',
	//'Bosnia And Herzegovina': 'BA',
	//'Botswana': 'BW',
	//'Bouvet Island': 'BV',
	//'British Indian Ocean Territory': 'IO',
	//'Brunei Darussalam': 'BN',
	//'Burkina Faso': 'BF',
	//'Burundi': 'BI',
	//'Cambodia': 'KH',
	//'Cameroon': 'CM',
	//'Cape Verde': 'CV',
	//'Cayman Islands': 'KY',
	//'Central African Republic': 'CF',
	//'Chad': 'TD',
	//'Chile': 'CL',
	//'Christmas Island': 'CX',
	//'Cocos (Keeling) Islands': 'CC',
	//'Comoros': 'KM',
	//'Congo': 'CG',
	//'Congo, Democratic Republic': 'CD',
	//'Cook Islands': 'CK',
	//'Costa Rica': 'CR',
	//'Cote D\'Ivoire': 'CI',
	//'Croatia': 'HR',
	//'Cyprus': 'CY',
	//'Denmark': 'DK',
	//'Djibouti': 'DJ',
	//'Dominica': 'DM',
	//'Dominican Republic': 'DO',
	//'Ecuador': 'EC',
	//'El Salvador': 'SV',
	//'Equatorial Guinea': 'GQ',
	//'Eritrea': 'ER',
	//'Estonia': 'EE',
	//'Ethiopia': 'ET',
	//'Falkland Islands': 'FK',
	//'Faroe Islands': 'FO',
	//'Fiji': 'FJ',
	//'Finland': 'FI',
	//'French Guiana': 'GF',
	//'French Polynesia': 'PF',
	//'French Southern Territories': 'TF',
	//'Gabon': 'GA',
	//'Gambia': 'GM',
	//'Georgia': 'GE',
	//'Ghana': 'GH',
	//'Gibraltar': 'GI',
	//'Greenland': 'GL',
	//'Grenada': 'GD',
	//'Guadeloupe': 'GP',
	//'Guam': 'GU',
	//'Guatemala': 'GT',
	//'Guernsey': 'GG',
	//'Guinea': 'GN',
	//'Guinea-Bissau': 'GW',
	//'Guyana': 'GY',
	//'Haiti': 'HT',
	//'Heard Island & Mcdonald Islands': 'HM',
	//'Holy See (Vatican City State)': 'VA',
	//'Honduras': 'HN',
	//'Iceland': 'IS',
	//'Iran, Islamic Republic Of': 'IR',
	//'Iraq': 'IQ',
	//'Isle Of Man': 'IM',
	//'Jamaica': 'JM',
	//'Jersey': 'JE',
	//'Jordan': 'JO',
	//'Kazakhstan': 'KZ',
	//'Kenya': 'KE',
	//'Kiribati': 'KI',
	//'Kuwait': 'KW',
	//'Kyrgyzstan': 'KG',
	//'Lao People\'s Democratic Republic': 'LA',
	//'Lebanon': 'LB',
	//'Lesotho': 'LS',
	//'Liberia': 'LR',
	//'Libyan Arab Jamahiriya': 'LY',
	//'Liechtenstein': 'LI',
	//'Luxembourg': 'LU',
	//'Macao': 'MO',
	//'Macedonia': 'MK',
	//'Madagascar': 'MG',
	//'Malawi': 'MW',
	//'Maldives': 'MV',
	//'Mali': 'ML',
	//'Malta': 'MT',
	//'Marshall Islands': 'MH',
	//'Martinique': 'MQ',
	//'Mauritania': 'MR',
	//'Mauritius': 'MU',
	//'Mayotte': 'YT',
	//'Micronesia, Federated States Of': 'FM',
	//'Moldova': 'MD',
	//'Monaco': 'MC',
	//'Mongolia': 'MN',
	//'Montenegro': 'ME',
	//'Montserrat': 'MS',
	//'Mozambique': 'MZ',
	//'Myanmar': 'MM',
	//'Namibia': 'NA',
	//'Nauru': 'NR',
	//'Nepal': 'NP',
	//'Netherlands Antilles': 'AN',
	//'New Caledonia': 'NC',
	//'Nicaragua': 'NI',
	//'Niger': 'NE',
	//'Niue': 'NU',
	//'Norfolk Island': 'NF',
	//'Northern Mariana Islands': 'MP',
	//'Oman': 'OM',
	//'Pakistan': 'PK',
	//'Palau': 'PW',
	//'Palestinian Territory, Occupied': 'PS',
	//'Panama': 'PA',
	//'Papua New Guinea': 'PG',
	//'Paraguay': 'PY',
	//'Peru': 'PE',
	//'Pitcairn': 'PN',
	//'Puerto Rico': 'PR',
	//'Qatar': 'QA',
	//'Reunion': 'RE',
	//'Rwanda': 'RW',
	//'Saint Barthelemy': 'BL',
	//'Saint Helena': 'SH',
	//'Saint Kitts And Nevis': 'KN',
	//'Saint Lucia': 'LC',
	//'Saint Martin': 'MF',
	//'Saint Pierre And Miquelon': 'PM',
	//'Saint Vincent And Grenadines': 'VC',
	//'Samoa': 'WS',
	//'San Marino': 'SM',
	//'Sao Tome And Principe': 'ST',
	//'Senegal': 'SN',
	//'Seychelles': 'SC',
	//'Sierra Leone': 'SL',
	//'Solomon Islands': 'SB',
	//'Somalia': 'SO',
	//'South Georgia And Sandwich Isl.': 'GS',
	//'Spain': 'ES',
	//'Sri Lanka': 'LK',
	//'Sudan': 'SD',
	//'Suriname': 'SR',
	//'Svalbard And Jan Mayen': 'SJ',
	//'Swaziland': 'SZ',
	//'Syrian Arab Republic': 'SY',
	//'Tajikistan': 'TJ',
	//'Tanzania': 'TZ',
	//'Timor-Leste': 'TL',
	//'Togo': 'TG',
	//'Tokelau': 'TK',
	//'Tonga': 'TO',
	//'Trinidad And Tobago': 'TT',
	//'Tunisia': 'TN',
	//'Turkmenistan': 'TM',
	//'Turks And Caicos Islands': 'TC',
	//'Tuvalu': 'TV',
	//'Uganda': 'UG',
	//'United States Outlying Islands': 'UM',
	//'Uruguay': 'UY',
	//'Uzbekistan': 'UZ',
	//'Vanuatu': 'VU',
	//'Vietnam': 'VN',
	//'Virgin Islands, British': 'VG',
	//'Virgin Islands, U.S.': 'VI',
	//'Wallis And Futuna': 'WF',
	//'Western Sahara': 'EH',
	//'Yemen': 'YE',
	//'Zambia': 'ZM',
	//'Zimbabwe': 'ZW'
};

module.exports = {
	getCountryCode: function (countryName) {
		if (isoCountries.hasOwnProperty(countryName)) {
			return isoCountries[countryName];
		} else {
			return countryName;
		}
	}
}